export const eventsList =  [
    {
      "eventId": "event1",
      "title": "Summer Music Festival",
      "description": "A lively outdoor music festival featuring top artists from around the world.",
      "organizerId": "user1",
      "category": "Music",
      "city": "Los Angeles",
      "venue": "Hollywood Bowl",
      "eventDate": "2024-11-15T18:00:00Z",
      "ticketPrice": 120.00,
      "isFree": false,
      "maxAttendees": 10000,
      "registeredAttendees": ["user2", "user3"],
      "eventImage": "url_to_image_1",
      "status": "upcoming",
      "createdAt": "2023-10-01T10:00:00Z",
      "updatedAt": "2023-10-05T12:00:00Z"
    },
    {
      "eventId": "event2",
      "title": "Tech Innovators Conference 2023",
      "description": "An annual conference for innovators in the tech industry.",
      "organizerId": "user4",
      "category": "Business",
      "city": "San Francisco",
      "venue": "Moscone Center",
      "eventDate": "2023-12-01T09:00:00Z",
      "ticketPrice": 300.00,
      "isFree": false,
      "maxAttendees": 5000,
      "registeredAttendees": ["user5"],
      "eventImage": "url_to_image_2",
      "status": "upcoming",
      "createdAt": "2023-09-25T08:30:00Z",
      "updatedAt": "2023-10-01T09:30:00Z"
    },
    {
      "eventId": "event3",
      "title": "Art Expo 2023",
      "description": "A grand exhibition showcasing contemporary artists and their works.",
      "organizerId": "user6",
      "category": "Art",
      "city": "New York",
      "venue": "Metropolitan Museum of Art",
      "eventDate": "2023-12-10T10:00:00Z",
      "ticketPrice": 50.00,
      "isFree": false,
      "maxAttendees": 2000,
      "registeredAttendees": ["user7", "user8"],
      "eventImage": "url_to_image_3",
      "status": "passed",
      "createdAt": "2023-09-15T11:00:00Z",
      "updatedAt": "2023-10-03T10:30:00Z"
    },
    {
      "eventId": "event4",
      "title": "Community Yoga in the Park",
      "description": "Free yoga sessions in Central Park for all fitness levels.",
      "organizerId": "user9",
      "category": "Health",
      "city": "New York",
      "venue": "Central Park",
      "eventDate": "2024-10-12T07:00:00Z",
      "ticketPrice": 0.00,
      "isFree": true,
      "maxAttendees": 200,
      "registeredAttendees": ["user10", "user11", "user12"],
      "eventImage": "url_to_image_4",
      "status": "upcoming",
      "createdAt": "2023-08-20T07:30:00Z",
      "updatedAt": "2023-09-25T11:00:00Z"
    },
    {
      "eventId": "event5",
      "title": "Startup Pitch Night",
      "description": "Join local startups as they pitch their ideas to potential investors.",
      "organizerId": "user13",
      "category": "Business",
      "city": "Austin",
      "venue": "Austin Convention Center",
      "eventDate": "2024-11-22T19:00:00Z",
      "ticketPrice": 20.00,
      "isFree": false,
      "maxAttendees": 500,
      "registeredAttendees": ["user14", "user15"],
      "eventImage": "url_to_image_5",
      "status": "upcoming",
      "createdAt": "2023-10-10T09:00:00Z",
      "updatedAt": "2023-10-18T08:45:00Z"
    },
    {
      "eventId": "event6",
      "title": "Food Truck Festival",
      "description": "Taste your way through a variety of cuisines at the annual food truck festival.",
      "organizerId": "user16",
      "category": "Food & Drink",
      "city": "Chicago",
      "venue": "Grant Park",
      "eventDate": "2024-10-20T12:00:00Z",
      "ticketPrice": 0.00,
      "isFree": true,
      "maxAttendees": 1000,
      "registeredAttendees": ["user17", "user18", "user19"],
      "eventImage": "url_to_image_6",
      "status": "upcoming",
      "createdAt": "2023-09-10T14:00:00Z",
      "updatedAt": "2023-09-20T09:45:00Z"
    },
    {
      "eventId": "event7",
      "title": "Blockchain and Cryptocurrency Workshop",
      "description": "A comprehensive workshop on blockchain and cryptocurrency technologies.",
      "organizerId": "user20",
      "category": "Education",
      "city": "Berlin",
      "venue": "TechHub Berlin",
      "eventDate": "2023-11-30T10:00:00Z",
      "ticketPrice": 75.00,
      "isFree": false,
      "maxAttendees": 300,
      "registeredAttendees": ["user21", "user22"],
      "eventImage": "url_to_image_7",
      "status": "upcoming",
      "createdAt": "2023-09-05T11:00:00Z",
      "updatedAt": "2023-10-01T10:15:00Z"
    },
    {
      "eventId": "event8",
      "title": "Outdoor Movie Night",
      "description": "Watch a classic movie under the stars. Bring your own blanket and snacks!",
      "organizerId": "user23",
      "category": "Entertainment",
      "city": "Sydney",
      "venue": "Royal Botanic Garden",
      "eventDate": "2023-11-25T20:00:00Z",
      "ticketPrice": 0.00,
      "isFree": true,
      "maxAttendees": 1000,
      "registeredAttendees": ["user24", "user25"],
      "eventImage": "url_to_image_8",
      "status": "upcoming",
      "createdAt": "2023-09-08T10:00:00Z",
      "updatedAt": "2023-09-28T09:50:00Z"
    },
    {
      "eventId": "event9",
      "title": "5K Charity Run",
      "description": "Join us for a 5K run to raise money for local charities.",
      "organizerId": "user26",
      "category": "Sports",
      "city": "London",
      "venue": "Hyde Park",
      "eventDate": "2024-11-18T08:00:00Z",
      "ticketPrice": 25.00,
      "isFree": false,
      "maxAttendees": 300,
      "registeredAttendees": ["user27", "user28", "user29"],
      "eventImage": "url_to_image_9",
      "status": "passed",
      "createdAt": "2023-09-18T10:15:00Z",
      "updatedAt": "2023-10-03T08:50:00Z"
    },
    {
      "eventId": "event10",
      "title": "Christmas Craft Fair",
      "description": "Browse handmade crafts and find unique gifts for the holiday season.",
      "organizerId": "user30",
      "category": "Shopping",
      "city": "Toronto",
      "venue": "Exhibition Place",
      "eventDate": "2023-12-15T10:00:00Z",
      "ticketPrice": 5.00,
      "isFree": false,
      "maxAttendees": 1000,
      "registeredAttendees": ["user31", "user32"],
      "eventImage": "url_to_image_10",
      "status": "upcoming",
      "createdAt": "2023-09-28T09:00:00Z",
      "updatedAt": "2023-10-05T12:30:00Z"
  },
        {
      "eventId": "event333",
      "title": "Art Expo 2024",
      "description": "A grand exhibition showcasing contemporary artists and their works.",
      "organizerId": "user6",
      "category": "Art",
      "city": "New York",
      "venue": "Metropolitan Museum of Art",
      "eventDate": "2024-11-15T10:00:00Z",
      "ticketPrice": 50.00,
      "isFree": false,
      "maxAttendees": 2000,
      "registeredAttendees": ["user7", "user8", "user9","user10"],
      "eventImage": "url_to_image_3",
      "status": "upcoming",
      "createdAt": "2023-09-15T11:00:00Z",
      "updatedAt": "2023-10-03T10:30:00Z"
    },
  ]